nelmio_cors:
    defaults:
        allow_origin: ['*'] # Autorise tout le monde (React, Postman, Mobile...)
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
            max_age: 3600