security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~  # Active la vérification du token sur TOUTES les routes /api
            
            # Optionnel : si tu veux que l'authenticator JWT soit le point d'entrée par défaut
            entry_point: jwt 

        main:
            lazy: true
            provider: app_user_provider

    access_control:
        # C'est ici que la magie opère :
        # 1. On laisse passer tout le monde sur /api/login (ton AuthController)
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        
        # 2. On laisse passer les requêtes OPTIONS (pour les erreurs CORS en React)
        - { path: ^/api, methods: [OPTIONS], roles: PUBLIC_ACCESS }
        
        # 3. Tout le reste de /api est BLOQUÉ si pas de token valide
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }